-- Seed comprehensive set of world languages into the locales table.
-- Uses ON CONFLICT to skip languages that already exist (en, de, es from initial migration).
-- New languages are inserted as inactive (is_active = false) so sysadmins
-- explicitly enable the ones they want available for site owners.

INSERT INTO locales (code, name, native_name, direction, is_active) VALUES
    -- Already seeded (will be skipped via ON CONFLICT)
    ('en', 'English', 'English', 'ltr', true),
    ('de', 'German', 'Deutsch', 'ltr', true),
    ('es', 'Spanish', 'Español', 'ltr', true),
    ('es-MX', 'Spanish (Mexico)', 'Español (México)', 'ltr', false),
    ('es-AR', 'Spanish (Argentina)', 'Español (Argentina)', 'ltr', false),
    ('es-CO', 'Spanish (Colombia)', 'Español (Colombia)', 'ltr', false),
    ('es-CL', 'Spanish (Chile)', 'Español (Chile)', 'ltr', false),
    -- European languages
    ('fr', 'French', 'Français', 'ltr', false),
    ('it', 'Italian', 'Italiano', 'ltr', false),
    ('pt', 'Portuguese', 'Português', 'ltr', false),
    ('pt-BR', 'Portuguese (Brazil)', 'Português (Brasil)', 'ltr', false),
    ('nl', 'Dutch', 'Nederlands', 'ltr', false),
    ('pl', 'Polish', 'Polski', 'ltr', false),
    ('ro', 'Romanian', 'Română', 'ltr', false),
    ('cs', 'Czech', 'Čeština', 'ltr', false),
    ('sk', 'Slovak', 'Slovenčina', 'ltr', false),
    ('hu', 'Hungarian', 'Magyar', 'ltr', false),
    ('bg', 'Bulgarian', 'Български', 'ltr', false),
    ('hr', 'Croatian', 'Hrvatski', 'ltr', false),
    ('sr', 'Serbian', 'Српски', 'ltr', false),
    ('sl', 'Slovenian', 'Slovenščina', 'ltr', false),
    ('uk', 'Ukrainian', 'Українська', 'ltr', false),
    ('el', 'Greek', 'Ελληνικά', 'ltr', false),
    ('da', 'Danish', 'Dansk', 'ltr', false),
    ('sv', 'Swedish', 'Svenska', 'ltr', false),
    ('nb', 'Norwegian Bokmål', 'Norsk bokmål', 'ltr', false),
    ('fi', 'Finnish', 'Suomi', 'ltr', false),
    ('et', 'Estonian', 'Eesti', 'ltr', false),
    ('lv', 'Latvian', 'Latviešu', 'ltr', false),
    ('lt', 'Lithuanian', 'Lietuvių', 'ltr', false),
    ('ga', 'Irish', 'Gaeilge', 'ltr', false),
    ('ca', 'Catalan', 'Català', 'ltr', false),
    ('eu', 'Basque', 'Euskara', 'ltr', false),
    ('gl', 'Galician', 'Galego', 'ltr', false),
    -- European regional variants
    ('de-AT', 'German (Austria)', 'Deutsch (Österreich)', 'ltr', false),
    ('de-CH', 'German (Switzerland)', 'Deutsch (Schweiz)', 'ltr', false),
    ('de-DE', 'German (Germany)', 'Deutsch (Deutschland)', 'ltr', false),
    ('en-US', 'English (US)', 'English (US)', 'ltr', false),
    ('en-GB', 'English (UK)', 'English (UK)', 'ltr', false),
    ('en-AU', 'English (Australia)', 'English (Australia)', 'ltr', false),
    ('fr-FR', 'French (France)', 'Français (France)', 'ltr', false),
    ('fr-CA', 'French (Canada)', 'Français (Canada)', 'ltr', false),
    ('fr-CH', 'French (Switzerland)', 'Français (Suisse)', 'ltr', false),
    ('fr-BE', 'French (Belgium)', 'Français (Belgique)', 'ltr', false),
    ('it-IT', 'Italian (Italy)', 'Italiano (Italia)', 'ltr', false),
    ('it-CH', 'Italian (Switzerland)', 'Italiano (Svizzera)', 'ltr', false),
    ('nl-NL', 'Dutch (Netherlands)', 'Nederlands (Nederland)', 'ltr', false),
    ('nl-BE', 'Dutch (Belgium)', 'Nederlands (België)', 'ltr', false),
    ('pt-PT', 'Portuguese (Portugal)', 'Português (Portugal)', 'ltr', false),
    -- Asian languages
    ('zh', 'Chinese (Simplified)', '中文 (简体)', 'ltr', false),
    ('zh-TW', 'Chinese (Traditional)', '中文 (繁體)', 'ltr', false),
    ('ja', 'Japanese', '日本語', 'ltr', false),
    ('ko', 'Korean', '한국어', 'ltr', false),
    ('vi', 'Vietnamese', 'Tiếng Việt', 'ltr', false),
    ('th', 'Thai', 'ไทย', 'ltr', false),
    ('id', 'Indonesian', 'Bahasa Indonesia', 'ltr', false),
    ('ms', 'Malay', 'Bahasa Melayu', 'ltr', false),
    ('tl', 'Filipino', 'Filipino', 'ltr', false),
    ('hi', 'Hindi', 'हिन्दी', 'ltr', false),
    ('bn', 'Bengali', 'বাংলা', 'ltr', false),
    ('ta', 'Tamil', 'தமிழ்', 'ltr', false),
    ('te', 'Telugu', 'తెలుగు', 'ltr', false),
    ('mr', 'Marathi', 'मराठी', 'ltr', false),
    ('gu', 'Gujarati', 'ગુજરાતી', 'ltr', false),
    ('kn', 'Kannada', 'ಕನ್ನಡ', 'ltr', false),
    ('ml', 'Malayalam', 'മലയാളം', 'ltr', false),
    -- RTL languages
    ('ar', 'Arabic', 'العربية', 'rtl', false),
    ('ar-SA', 'Arabic (Saudi Arabia)', 'العربية (السعودية)', 'rtl', false),
    ('ar-EG', 'Arabic (Egypt)', 'العربية (مصر)', 'rtl', false),
    ('ar-MA', 'Arabic (Morocco)', 'العربية (المغرب)', 'rtl', false),
    ('he', 'Hebrew', 'עברית', 'rtl', false),
    ('fa', 'Persian', 'فارسی', 'rtl', false),
    ('ur', 'Urdu', 'اردو', 'rtl', false),
    -- African languages
    ('sw', 'Swahili', 'Kiswahili', 'ltr', false),
    ('am', 'Amharic', 'አማርኛ', 'ltr', false),
    -- Turkic languages
    ('tr', 'Turkish', 'Türkçe', 'ltr', false),
    ('az', 'Azerbaijani', 'Azərbaycan dili', 'ltr', false),
    ('kk', 'Kazakh', 'Қазақ тілі', 'ltr', false),
    -- Other
    ('ru', 'Russian', 'Русский', 'ltr', false),
    ('ka', 'Georgian', 'ქართული', 'ltr', false),
    ('hy', 'Armenian', 'Հայերեն', 'ltr', false),
    -- Constructed & fictional languages
    ('tlh', 'Klingon', 'tlhIngan Hol', 'ltr', false),
    ('eo', 'Esperanto', 'Esperanto', 'ltr', false),
    ('ia', 'Interlingua', 'Interlingua', 'ltr', false),
    ('vo', 'Volapük', 'Volapük', 'ltr', false),
    ('jbo', 'Lojban', 'la .lojban.', 'ltr', false),
    ('tok', 'Toki Pona', 'toki pona', 'ltr', false),
    ('la', 'Latin', 'Latina', 'ltr', false)
ON CONFLICT (code) DO NOTHING;
