'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ForjaContactCustomEvent, type ForjaNavCustomEvent, type ForjaNewsletterCustomEvent } from "@forjacms/sections";
import type { Components } from "@forjacms/sections/dist/components";
import { ForjaBlog as ForjaBlogElement, defineCustomElement as defineForjaBlog } from "@forjacms/sections/dist/components/forja-blog.js";
import { ForjaContact as ForjaContactElement, defineCustomElement as defineForjaContact } from "@forjacms/sections/dist/components/forja-contact.js";
import { ForjaCta as ForjaCtaElement, defineCustomElement as defineForjaCta } from "@forjacms/sections/dist/components/forja-cta.js";
import { ForjaDivider as ForjaDividerElement, defineCustomElement as defineForjaDivider } from "@forjacms/sections/dist/components/forja-divider.js";
import { ForjaFaq as ForjaFaqElement, defineCustomElement as defineForjaFaq } from "@forjacms/sections/dist/components/forja-faq.js";
import { ForjaFeatures as ForjaFeaturesElement, defineCustomElement as defineForjaFeatures } from "@forjacms/sections/dist/components/forja-features.js";
import { ForjaFooter as ForjaFooterElement, defineCustomElement as defineForjaFooter } from "@forjacms/sections/dist/components/forja-footer.js";
import { ForjaGallery as ForjaGalleryElement, defineCustomElement as defineForjaGallery } from "@forjacms/sections/dist/components/forja-gallery.js";
import { ForjaHero as ForjaHeroElement, defineCustomElement as defineForjaHero } from "@forjacms/sections/dist/components/forja-hero.js";
import { ForjaLegal as ForjaLegalElement, defineCustomElement as defineForjaLegal } from "@forjacms/sections/dist/components/forja-legal.js";
import { ForjaLogoCloud as ForjaLogoCloudElement, defineCustomElement as defineForjaLogoCloud } from "@forjacms/sections/dist/components/forja-logo-cloud.js";
import { ForjaNav as ForjaNavElement, defineCustomElement as defineForjaNav } from "@forjacms/sections/dist/components/forja-nav.js";
import { ForjaNewsletter as ForjaNewsletterElement, defineCustomElement as defineForjaNewsletter } from "@forjacms/sections/dist/components/forja-newsletter.js";
import { ForjaPortfolio as ForjaPortfolioElement, defineCustomElement as defineForjaPortfolio } from "@forjacms/sections/dist/components/forja-portfolio.js";
import { ForjaPricing as ForjaPricingElement, defineCustomElement as defineForjaPricing } from "@forjacms/sections/dist/components/forja-pricing.js";
import { ForjaProjects as ForjaProjectsElement, defineCustomElement as defineForjaProjects } from "@forjacms/sections/dist/components/forja-projects.js";
import { ForjaSectionRenderer as ForjaSectionRendererElement, defineCustomElement as defineForjaSectionRenderer } from "@forjacms/sections/dist/components/forja-section-renderer.js";
import { ForjaStats as ForjaStatsElement, defineCustomElement as defineForjaStats } from "@forjacms/sections/dist/components/forja-stats.js";
import { ForjaTagCloud as ForjaTagCloudElement, defineCustomElement as defineForjaTagCloud } from "@forjacms/sections/dist/components/forja-tag-cloud.js";
import { ForjaTeam as ForjaTeamElement, defineCustomElement as defineForjaTeam } from "@forjacms/sections/dist/components/forja-team.js";
import { ForjaTestimonials as ForjaTestimonialsElement, defineCustomElement as defineForjaTestimonials } from "@forjacms/sections/dist/components/forja-testimonials.js";
import { ForjaTextBlock as ForjaTextBlockElement, defineCustomElement as defineForjaTextBlock } from "@forjacms/sections/dist/components/forja-text-block.js";
import { ForjaTimeline as ForjaTimelineElement, defineCustomElement as defineForjaTimeline } from "@forjacms/sections/dist/components/forja-timeline.js";
import { ForjaVideo as ForjaVideoElement, defineCustomElement as defineForjaVideo } from "@forjacms/sections/dist/components/forja-video.js";

export type ForjaBlogEvents = NonNullable<unknown>;

export const ForjaBlog: StencilReactComponent<ForjaBlogElement, ForjaBlogEvents, Components.ForjaBlog> = /*@__PURE__*/ createComponent<ForjaBlogElement, ForjaBlogEvents, Components.ForjaBlog>({
    tagName: 'forja-blog',
    elementClass: ForjaBlogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaBlogEvents,
    defineCustomElement: defineForjaBlog
});

export type ForjaContactEvents = { onForjaSubmit: EventName<ForjaContactCustomEvent<FormData>> };

export const ForjaContact: StencilReactComponent<ForjaContactElement, ForjaContactEvents, Components.ForjaContact> = /*@__PURE__*/ createComponent<ForjaContactElement, ForjaContactEvents, Components.ForjaContact>({
    tagName: 'forja-contact',
    elementClass: ForjaContactElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onForjaSubmit: 'forjaSubmit' } as ForjaContactEvents,
    defineCustomElement: defineForjaContact
});

export type ForjaCtaEvents = NonNullable<unknown>;

export const ForjaCta: StencilReactComponent<ForjaCtaElement, ForjaCtaEvents, Components.ForjaCta> = /*@__PURE__*/ createComponent<ForjaCtaElement, ForjaCtaEvents, Components.ForjaCta>({
    tagName: 'forja-cta',
    elementClass: ForjaCtaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaCtaEvents,
    defineCustomElement: defineForjaCta
});

export type ForjaDividerEvents = NonNullable<unknown>;

export const ForjaDivider: StencilReactComponent<ForjaDividerElement, ForjaDividerEvents, Components.ForjaDivider> = /*@__PURE__*/ createComponent<ForjaDividerElement, ForjaDividerEvents, Components.ForjaDivider>({
    tagName: 'forja-divider',
    elementClass: ForjaDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaDividerEvents,
    defineCustomElement: defineForjaDivider
});

export type ForjaFaqEvents = NonNullable<unknown>;

export const ForjaFaq: StencilReactComponent<ForjaFaqElement, ForjaFaqEvents, Components.ForjaFaq> = /*@__PURE__*/ createComponent<ForjaFaqElement, ForjaFaqEvents, Components.ForjaFaq>({
    tagName: 'forja-faq',
    elementClass: ForjaFaqElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaFaqEvents,
    defineCustomElement: defineForjaFaq
});

export type ForjaFeaturesEvents = NonNullable<unknown>;

export const ForjaFeatures: StencilReactComponent<ForjaFeaturesElement, ForjaFeaturesEvents, Components.ForjaFeatures> = /*@__PURE__*/ createComponent<ForjaFeaturesElement, ForjaFeaturesEvents, Components.ForjaFeatures>({
    tagName: 'forja-features',
    elementClass: ForjaFeaturesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaFeaturesEvents,
    defineCustomElement: defineForjaFeatures
});

export type ForjaFooterEvents = NonNullable<unknown>;

export const ForjaFooter: StencilReactComponent<ForjaFooterElement, ForjaFooterEvents, Components.ForjaFooter> = /*@__PURE__*/ createComponent<ForjaFooterElement, ForjaFooterEvents, Components.ForjaFooter>({
    tagName: 'forja-footer',
    elementClass: ForjaFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaFooterEvents,
    defineCustomElement: defineForjaFooter
});

export type ForjaGalleryEvents = NonNullable<unknown>;

export const ForjaGallery: StencilReactComponent<ForjaGalleryElement, ForjaGalleryEvents, Components.ForjaGallery> = /*@__PURE__*/ createComponent<ForjaGalleryElement, ForjaGalleryEvents, Components.ForjaGallery>({
    tagName: 'forja-gallery',
    elementClass: ForjaGalleryElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaGalleryEvents,
    defineCustomElement: defineForjaGallery
});

export type ForjaHeroEvents = NonNullable<unknown>;

export const ForjaHero: StencilReactComponent<ForjaHeroElement, ForjaHeroEvents, Components.ForjaHero> = /*@__PURE__*/ createComponent<ForjaHeroElement, ForjaHeroEvents, Components.ForjaHero>({
    tagName: 'forja-hero',
    elementClass: ForjaHeroElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaHeroEvents,
    defineCustomElement: defineForjaHero
});

export type ForjaLegalEvents = NonNullable<unknown>;

export const ForjaLegal: StencilReactComponent<ForjaLegalElement, ForjaLegalEvents, Components.ForjaLegal> = /*@__PURE__*/ createComponent<ForjaLegalElement, ForjaLegalEvents, Components.ForjaLegal>({
    tagName: 'forja-legal',
    elementClass: ForjaLegalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaLegalEvents,
    defineCustomElement: defineForjaLegal
});

export type ForjaLogoCloudEvents = NonNullable<unknown>;

export const ForjaLogoCloud: StencilReactComponent<ForjaLogoCloudElement, ForjaLogoCloudEvents, Components.ForjaLogoCloud> = /*@__PURE__*/ createComponent<ForjaLogoCloudElement, ForjaLogoCloudEvents, Components.ForjaLogoCloud>({
    tagName: 'forja-logo-cloud',
    elementClass: ForjaLogoCloudElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaLogoCloudEvents,
    defineCustomElement: defineForjaLogoCloud
});

export type ForjaNavEvents = {
    onForjaThemeToggle: EventName<ForjaNavCustomEvent<void>>,
    onForjaLocaleChange: EventName<ForjaNavCustomEvent<string>>
};

export const ForjaNav: StencilReactComponent<ForjaNavElement, ForjaNavEvents, Components.ForjaNav> = /*@__PURE__*/ createComponent<ForjaNavElement, ForjaNavEvents, Components.ForjaNav>({
    tagName: 'forja-nav',
    elementClass: ForjaNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onForjaThemeToggle: 'forjaThemeToggle',
        onForjaLocaleChange: 'forjaLocaleChange'
    } as ForjaNavEvents,
    defineCustomElement: defineForjaNav
});

export type ForjaNewsletterEvents = { onForjaSubmit: EventName<ForjaNewsletterCustomEvent<FormData>> };

export const ForjaNewsletter: StencilReactComponent<ForjaNewsletterElement, ForjaNewsletterEvents, Components.ForjaNewsletter> = /*@__PURE__*/ createComponent<ForjaNewsletterElement, ForjaNewsletterEvents, Components.ForjaNewsletter>({
    tagName: 'forja-newsletter',
    elementClass: ForjaNewsletterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onForjaSubmit: 'forjaSubmit' } as ForjaNewsletterEvents,
    defineCustomElement: defineForjaNewsletter
});

export type ForjaPortfolioEvents = NonNullable<unknown>;

export const ForjaPortfolio: StencilReactComponent<ForjaPortfolioElement, ForjaPortfolioEvents, Components.ForjaPortfolio> = /*@__PURE__*/ createComponent<ForjaPortfolioElement, ForjaPortfolioEvents, Components.ForjaPortfolio>({
    tagName: 'forja-portfolio',
    elementClass: ForjaPortfolioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaPortfolioEvents,
    defineCustomElement: defineForjaPortfolio
});

export type ForjaPricingEvents = NonNullable<unknown>;

export const ForjaPricing: StencilReactComponent<ForjaPricingElement, ForjaPricingEvents, Components.ForjaPricing> = /*@__PURE__*/ createComponent<ForjaPricingElement, ForjaPricingEvents, Components.ForjaPricing>({
    tagName: 'forja-pricing',
    elementClass: ForjaPricingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaPricingEvents,
    defineCustomElement: defineForjaPricing
});

export type ForjaProjectsEvents = NonNullable<unknown>;

export const ForjaProjects: StencilReactComponent<ForjaProjectsElement, ForjaProjectsEvents, Components.ForjaProjects> = /*@__PURE__*/ createComponent<ForjaProjectsElement, ForjaProjectsEvents, Components.ForjaProjects>({
    tagName: 'forja-projects',
    elementClass: ForjaProjectsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaProjectsEvents,
    defineCustomElement: defineForjaProjects
});

export type ForjaSectionRendererEvents = NonNullable<unknown>;

export const ForjaSectionRenderer: StencilReactComponent<ForjaSectionRendererElement, ForjaSectionRendererEvents, Components.ForjaSectionRenderer> = /*@__PURE__*/ createComponent<ForjaSectionRendererElement, ForjaSectionRendererEvents, Components.ForjaSectionRenderer>({
    tagName: 'forja-section-renderer',
    elementClass: ForjaSectionRendererElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaSectionRendererEvents,
    defineCustomElement: defineForjaSectionRenderer
});

export type ForjaStatsEvents = NonNullable<unknown>;

export const ForjaStats: StencilReactComponent<ForjaStatsElement, ForjaStatsEvents, Components.ForjaStats> = /*@__PURE__*/ createComponent<ForjaStatsElement, ForjaStatsEvents, Components.ForjaStats>({
    tagName: 'forja-stats',
    elementClass: ForjaStatsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaStatsEvents,
    defineCustomElement: defineForjaStats
});

export type ForjaTagCloudEvents = NonNullable<unknown>;

export const ForjaTagCloud: StencilReactComponent<ForjaTagCloudElement, ForjaTagCloudEvents, Components.ForjaTagCloud> = /*@__PURE__*/ createComponent<ForjaTagCloudElement, ForjaTagCloudEvents, Components.ForjaTagCloud>({
    tagName: 'forja-tag-cloud',
    elementClass: ForjaTagCloudElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaTagCloudEvents,
    defineCustomElement: defineForjaTagCloud
});

export type ForjaTeamEvents = NonNullable<unknown>;

export const ForjaTeam: StencilReactComponent<ForjaTeamElement, ForjaTeamEvents, Components.ForjaTeam> = /*@__PURE__*/ createComponent<ForjaTeamElement, ForjaTeamEvents, Components.ForjaTeam>({
    tagName: 'forja-team',
    elementClass: ForjaTeamElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaTeamEvents,
    defineCustomElement: defineForjaTeam
});

export type ForjaTestimonialsEvents = NonNullable<unknown>;

export const ForjaTestimonials: StencilReactComponent<ForjaTestimonialsElement, ForjaTestimonialsEvents, Components.ForjaTestimonials> = /*@__PURE__*/ createComponent<ForjaTestimonialsElement, ForjaTestimonialsEvents, Components.ForjaTestimonials>({
    tagName: 'forja-testimonials',
    elementClass: ForjaTestimonialsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaTestimonialsEvents,
    defineCustomElement: defineForjaTestimonials
});

export type ForjaTextBlockEvents = NonNullable<unknown>;

export const ForjaTextBlock: StencilReactComponent<ForjaTextBlockElement, ForjaTextBlockEvents, Components.ForjaTextBlock> = /*@__PURE__*/ createComponent<ForjaTextBlockElement, ForjaTextBlockEvents, Components.ForjaTextBlock>({
    tagName: 'forja-text-block',
    elementClass: ForjaTextBlockElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaTextBlockEvents,
    defineCustomElement: defineForjaTextBlock
});

export type ForjaTimelineEvents = NonNullable<unknown>;

export const ForjaTimeline: StencilReactComponent<ForjaTimelineElement, ForjaTimelineEvents, Components.ForjaTimeline> = /*@__PURE__*/ createComponent<ForjaTimelineElement, ForjaTimelineEvents, Components.ForjaTimeline>({
    tagName: 'forja-timeline',
    elementClass: ForjaTimelineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaTimelineEvents,
    defineCustomElement: defineForjaTimeline
});

export type ForjaVideoEvents = NonNullable<unknown>;

export const ForjaVideo: StencilReactComponent<ForjaVideoElement, ForjaVideoEvents, Components.ForjaVideo> = /*@__PURE__*/ createComponent<ForjaVideoElement, ForjaVideoEvents, Components.ForjaVideo>({
    tagName: 'forja-video',
    elementClass: ForjaVideoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ForjaVideoEvents,
    defineCustomElement: defineForjaVideo
});
