#!/usr/bin/env bash
# Forja — Production environment initializer
#
# Generates a .env file with secure random secrets and validates prerequisites.
#
# Usage:
#   ./scripts/forja-init.sh           # interactive mode
#   ./scripts/forja-init.sh --yes     # non-interactive with defaults

set -euo pipefail

ENV_FILE=".env"
COMPOSE_FILE="docker-compose.prod.yml"

# Colors (disabled if not a terminal)
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  BOLD='\033[1m'
  NC='\033[0m'
else
  GREEN='' YELLOW='' RED='' BOLD='' NC=''
fi

info()  { echo -e "${GREEN}[ok]${NC} $1"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $1"; }
error() { echo -e "${RED}[error]${NC} $1" >&2; }
header() { echo -e "\n${BOLD}$1${NC}"; }

# Parse arguments
AUTO_YES=false
for arg in "$@"; do
  case "$arg" in
    --yes|-y) AUTO_YES=true ;;
  esac
done

confirm() {
  if $AUTO_YES; then return 0; fi
  read -rp "$1 [Y/n] " answer
  case "$answer" in
    [Nn]*) return 1 ;;
    *) return 0 ;;
  esac
}

generate_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

# --- Prerequisite checks ---
header "Checking prerequisites..."

MISSING=0

if command -v docker &>/dev/null; then
  DOCKER_VERSION=$(docker --version 2>/dev/null | sed 's/[^0-9.]//g' | cut -d. -f1-2)
  info "Docker $DOCKER_VERSION"
else
  error "Docker is not installed. Install from https://docs.docker.com/get-docker/"
  MISSING=1
fi

if docker compose version &>/dev/null; then
  COMPOSE_VERSION=$(docker compose version --short 2>/dev/null)
  info "Docker Compose $COMPOSE_VERSION"
else
  error "Docker Compose v2 is not installed. It's included with Docker Desktop."
  MISSING=1
fi

DISK_FREE_MB=$(df -m . 2>/dev/null | awk 'NR==2 {print $4}')
if [ -n "$DISK_FREE_MB" ] && [ "$DISK_FREE_MB" -gt 2048 ]; then
  info "Disk space: ${DISK_FREE_MB}MB free"
else
  warn "Less than 2GB free disk space (${DISK_FREE_MB:-unknown}MB). Docker images need ~1.5GB."
fi

if [ "$MISSING" -ne 0 ]; then
  error "Missing prerequisites. Install the above and try again."
  exit 1
fi

# --- Generate .env ---
header "Generating environment file..."

if [ -f "$ENV_FILE" ]; then
  if confirm "  $ENV_FILE already exists. Overwrite?"; then
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%s)"
    info "Backed up existing $ENV_FILE"
  else
    info "Keeping existing $ENV_FILE"
    echo ""
    echo -e "Run ${BOLD}docker compose -f $COMPOSE_FILE up -d${NC} to start Forja."
    exit 0
  fi
fi

PG_PASSWORD=$(generate_secret)

cat > "$ENV_FILE" <<EOF
# Forja production environment
# Generated by forja-init.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# PostgreSQL
POSTGRES_USER=forja
POSTGRES_PASSWORD=$PG_PASSWORD
POSTGRES_DB=forja

# Application
APP_PORT=8000
APP__CORS_ORIGINS=*

# Storage (local filesystem by default)
STORAGE_PROVIDER=local

# Clerk authentication (optional — uncomment and fill in to enable)
# CLERK_SECRET_KEY=sk_live_...
# CLERK_PUBLISHABLE_KEY=pk_live_...
# SYSTEM_ADMIN_CLERK_IDS=user_...
EOF

info "Created $ENV_FILE with secure random password"

# --- Verify compose file ---
if [ ! -f "$COMPOSE_FILE" ]; then
  warn "$COMPOSE_FILE not found in current directory."
  echo "  Make sure you run this script from the Forja project root."
fi

# --- Summary ---
header "Ready!"
echo ""
echo "  Start Forja:"
echo -e "    ${BOLD}docker compose -f $COMPOSE_FILE up -d${NC}"
echo ""
echo "  Verify:"
echo -e "    ${BOLD}curl http://localhost:8000/health${NC}"
echo ""
echo "  Open the admin dashboard:"
echo -e "    ${BOLD}http://localhost:8000/dashboard${NC}"
echo ""
echo "  View logs:"
echo -e "    ${BOLD}docker compose -f $COMPOSE_FILE logs -f${NC}"
echo ""
echo "  Stop:"
echo -e "    ${BOLD}docker compose -f $COMPOSE_FILE down${NC}"
echo ""
